# pyegui is built and verified in GitHub Actions only.
#
# There is deliberately no Rust toolchain on a developer machine for this
# repository, so any target that needs `cargo` or `maturin` cannot succeed
# locally. Those targets are kept only so the error is explicit: they used to
# run `.venv/bin/maturin` and shell out to docker, which failed much later and
# much less clearly.
#
# The verdict on whether the code compiles is a workflow run:
#
#     git push fork feature/<name>
#     gh run list --repo ChetanKnowIT/pyegui --branch feature/<name>
#
# See docs/development.rst. Do not trust build output that did not come from a
# CI run.

# Refuses to run, and says where the build actually happens.
needs-rust:
	@echo "pyegui builds in GitHub Actions only; there is no local Rust toolchain." >&2
	@echo "" >&2
	@echo "To build and verify, push and read the workflow run:" >&2
	@echo "    git push fork feature/<name>" >&2
	@echo "    gh run list --repo ChetanKnowIT/pyegui --branch feature/<name>" >&2
	@echo "" >&2
	@echo "See docs/development.rst." >&2
	@exit 1

build: needs-rust
build-manylinux: needs-rust
develop: needs-rust
develop-release: needs-rust

# --- targets that need no Rust toolchain ---------------------------------

venv:
	python3 -m venv .venv
	.venv/bin/pip install sphinx sphinx-rtd-theme

python:
	.venv/bin/python

debug:
	.venv/bin/python debug.py

doc:
	.venv/bin/sphinx-build -v ./docs/ ./docs/_build

upload:
	python3 -m twine upload --verbose dist/*

upload-test:
	python3 -m twine upload --verbose --repository testpypi dist/*

# PyPI uploads happen in the autogenerated CI.yml on a tag push, not by hand.
# See docs/development.rst.

.PHONY: needs-rust build build-manylinux develop develop-release venv python debug doc upload upload-test